#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/yoo/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

nm-applet &
# feh --bg-scale /usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/1920x1200.svg &
# feh --bg-scale /usr/share/desktop-base/joy-inksplat-theme/wallpaper/contents/images/1920x1200.svg &

# To view and set the desired wallpaper from a specific directory recursively, run: 
# $ nitrogen /path/to/image/directory/

# To view and set the desired wallpaper from a specific directory non-recursively, run:
# $ nitrogen --no-recurse /path/to/image/directory/

# Freeze with dual monitors
# $ rm -r ~/.config/nitrogen/

nitrogen --restore &


#wmnd  &
#wmcpuload &
#wmmoonclock &
#wmweather -s KBKE &
gnome-sound-applet &
#gnome-volume-manager &

# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

/home/yoo/docklight_3.0.orig/src/docklight  1 &

compton -b
#xcompmgr -c &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
xrandr --output VGA-0 --off --output LVDS-0 --mode 1920x1080 --pos 2560x0 --rotate normal --output DP-5 --off --output DP-4 --off --output DP-3 --off --output DP-2 --off --output DP-1 --off --output DP-0 --primary --mode 2560x1440 --pos 0x0 --rotate normal

# launch the policykit authentication agent for pkexec
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/yoo/.fluxbox/log"



