#!/bin/bash

#--------------------
# needs root access
#--------------------

echo "install all software from debian repo"
apt install \
build-essential \
cmake \
git \
gitk \
libgtkmm-3.0-dev \
libwnck-3-dev \
autotools-dev \
autoconf \
libtool \
gettext \
autopoint \
intltool \
clang-format \
vim \
vim-athena \
fortunes \
cowsay \
fortune-mod \
compton \
firefox-esr \
pavucontrol \
nemo \
redshift \
gedit \
firefox-esr \
gnome-terminal \
openbox \
compton \
lightdm \
gdm3 \
gnome-settings-daemon \
xfce4-panel \
xfce4-power-manager \
nitrogen -y
echo "done"

echo "install docker"
apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-get update
apt-get install docker-ce


echo "done"
exit






