#!/bin/bash

#--------------------
# needs root access
#--------------------

echo "install all software from debian repo"
apt install \
build-essential \
cmake \
git \
gitk \
libgtkmm-3.0-dev \
libwnck-3-dev \
autotools-dev \
autoconf \
libtool \
gettext \
autopoint \
intltool \
clang-format \
vim \
vim-athena \
fortunes \
cowsay \
fortune-mod \
compton \
firefox-esr \
pavucontrol \
nemo \
thunar \
redshift \
gedit \
firefox-esr \
gnome-terminal \
openbox \
compton \
lightdm \
#gdm3 \
arandr \
grub-customizer \
gnome-settings-daemon \
xfce4-panel \
xfce4-power-manager \
xfce4-whiskermenu-plugin \
xfce4-datetime-plugin \
xfce4-battery-plugin \
xfce4-indicator-plugin \
xfce4-pulseaudio-plugin \
lxappearance \
nitrogen \
policykit-1-gnome \
chromium \
geany \
transmission -y
lxinput \
lxrandr \
apt update
apt autoremove -y

echo "done"

echo "install docker"
apt install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
apt-get update
apt-get install docker.io -y


echo "done"

#/sbin/shutdown -r now

exit






