#!/bin/bash

ans=$(zenity \
    --title "End Session" \
    --text="Choose end session option" \
    --list --radiolist \
    --column "" --column "" --hide-header \
    FALSE Logout \
    FALSE Restart \
    TRUE Shutdown)

case $ans in
    "Logout")   openbox --exit;;
    "Restart")  systemctl reboot;;
    "Shutdown") systemctl poweroff;;
esac
